const collegeData = [
    {
      "rank": 1,
      "name": "IIT Madras - Indian Institute of Technology - [IITM]",
      "location": "Chennai, Tamil Nadu",
      "approval": "AICTE Approved",
      "fees": "₹ 2,42,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 21,48,000",
      "highest_package": "₹ 1,98,00,000",
      "placement": "4.2 / 5 Based on 365 User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#3th/275 in India The Week 2024"
    },
    {
      "rank": 2,
      "name": "IIT Delhi - Indian Institute of Technology [IITD]",
      "location": "New Delhi, Delhi NCR",
      "approval": "",
      "fees": "₹ 1,90,300",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "₹ 25,82,000",
      "highest_package": "₹ 2,00,00,000",
      "placement": "4.3 / 5 Based on 560 User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#1th/31 in India Indiatoday 2024"
    },
    {
      "rank": 3,
      "name": "IIT Bombay - Indian Institute of Technology - [IITB]",
      "location": "Mumbai, Maharashtra",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,30,700",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 21,82,000",
      "highest_package": "₹ 3,67,00,000",
      "placement": "4.4 / 5 Based on 339 User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#2th/31 in India Indiatoday 2024"
    },
    {
      "rank": 4,
      "name": "IIT Kharagpur - Indian Institute of Technology - [IITKGP]",
      "location": "Kharagpur, West Bengal",
      "approval": "AICTE, UGC, NBA Approved",
      "fees": "₹ 27,650",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "",
      "highest_package": "₹ 2,60,00,000",
      "placement": "4.3 / 5 Based on 684 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#4th/31 in India Indiatoday 2024"
    },
    {
      "rank": 5,
      "name": "IIT Kanpur - Indian Institute of Technology - [IITK]",
      "location": "Kanpur, Uttar Pradesh",
      "approval": "UGC Approved",
      "fees": "₹ 2,29,970",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "",
      "highest_package": "₹ 1,90,00,000",
      "placement": "4.4 / 5 Based on 430 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#3th/31 in India Indiatoday 2024"
    },
    {
      "rank": 6,
      "name": "IIT Roorkee - Indian Institute of Technology - [IITR]",
      "location": "Roorkee, Uttarakhand",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,30,100",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 18,34,000",
      "highest_package": "₹ 1,30,00,000",
      "placement": "4.3 / 5 Based on 496 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#5th/31 in India Indiatoday 2024"
    },
    {
      "rank": 7,
      "name": "BITS Pilani (Pilani Campus)",
      "location": "Pilani, Rajasthan",
      "approval": "UGC Approved",
      "fees": "₹ 6,03,775",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "₹ 30,37,000",
      "highest_package": "₹ 60,75,000",
      "placement": "4.4 / 5 Based on 618 User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#1th/253 in India Indiatoday 2024"
    },
    {
      "rank": 8,
      "name": "IIT Guwahati - Indian Institute of Technology - [IITG]",
      "location": "Guwahati, Assam",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 98,250",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "",
      "highest_package": "₹ 2,40,00,000",
      "placement": "4.3 / 5 Based on 394 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#6th/31 in India Indiatoday 2024"
    },
    {
      "rank": 9,
      "name": "IIT Hyderabad - Indian Institute of Technology - [IITH]",
      "location": "Hyderabad, Telangana",
      "approval": "UGC Approved",
      "fees": "₹ 53,888",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "₹ 20,07,000",
      "highest_package": "₹ 63,78,000",
      "placement": "4.3 / 5 Based on 190 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#8th/300 in India NIRF 2024"
    },
    {
      "rank": 10,
      "name": "College of Engineering, Anna University - [CEG]",
      "location": "Chennai, Tamil Nadu",
      "approval": "AICTE Approved",
      "fees": "₹ 47,200",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "",
      "highest_package": "",
      "placement": "4.2 / 5 Based on 103 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#12th/275 in India The Week 2024"
    }
  
  ,
  
  
    {
      "rank": 11,
      "name": "Indian Institute of Science - IISc]",
      "location": "Bangalore, Karnataka",
      "approval": "AICTE Approved",
      "fees": "₹ 29,200",
      "course": "ME/M.Tech- 1st Year Fees",
      "average_package": "₹ 23,00,000",
      "highest_package": "₹ 85,00,000",
      "placement": "4.5 / 5 Based on 60 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#2th/300 in India NIRF 2024"
    },
    {
      "rank": 12,
      "name": "IIT (BHU) Varanasi - Indian Institute of Technology - [IITBHU]",
      "location": "Varanasi, Uttar Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,28,600",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 14,00,000",
      "highest_package": "₹ 1,27,00,000",
      "placement": "4.2 / 5 Based on 428 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#14th/31 in India Indiatoday 2024"
    },
    {
      "rank": 13,
      "name": "IIIT Hyderabad - International Institute of Information Technology - [IIITH]",
      "location": "Hyderabad, Telangana",
      "approval": "AICTE Approved",
      "fees": "₹ 3,00,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 32,00,000",
      "highest_package": "₹ 2,08,00,000",
      "placement": "4.4 / 5 Based on 154 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#2th/253 in India Indiatoday 2024"
    },
    {
      "rank": 14,
      "name": "Delhi Technological University - [DTU]",
      "location": "New Delhi, Delhi NCR",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,00,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 15,00,000",
      "highest_package": "₹ 2,00,00,000",
      "placement": "4.3 / 5 Based on 543 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#3th/300 in India NIRF 2024"
    },
    {
      "rank": 15,
      "name": "National Institute of Technology - [NIT]",
      "location": "Tiruchirappalli, Tamil Nadu",
      "approval": "AICTE Approved",
      "fees": "₹ 1,49,250",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 10,81,000",
      "highest_package": "₹ 56,00,000",
      "placement": "4.5 / 5 Based on 763 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#1th/300 in India NIRF 2024"
    },
    {
      "rank": 16,
      "name": "IIT Indore - Indian Institute of Technology - [IITI]",
      "location": "Indore, Madhya Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,21,360",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 25,00,000",
      "highest_package": "₹ 1,30,00,000",
      "placement": "4.3 / 5 Based on 123 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#7th/300 in India NIRF 2024"
    },
    {
      "rank": 17,
      "name": "National Institute of Technology - [NIT]",
      "location": "Karnataka",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,40,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 9,86,000",
      "highest_package": "₹ 50,00,000",
      "placement": "4.4 / 5 Based on 679 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#3th/275 in India The Week 2024"
    },
    {
      "rank": 18,
      "name": "Vellore Institute of Technology - [VIT]",
      "location": "Vellore, Tamil Nadu",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,98,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,30,000",
      "highest_package": "₹ 44,00,000",
      "placement": "4.2 / 5 Based on 796 User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#4th/275 in India The Week 2024"
    },
    {
      "rank": 19,
      "name": "National Institute of Technology - [NIT]",
      "location": "Rourkela, Odisha",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,49,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 10,10,000",
      "highest_package": "₹ 42,00,000",
      "placement": "4.3 / 5 Based on 789 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#5th/300 in India NIRF 2024"
    },
    {
      "rank": 20,
      "name": "IIT Bhubaneswar - Indian Institute of Technology - [IITBBS]",
      "location": "Bhubaneswar, Odisha",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,16,320",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 19,00,000",
      "highest_package": "₹ 48,00,000",
      "placement": "4.3 / 5 Based on 246 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#11th/31 in India Indiatoday 2024"
    }
  ,
  
  
  
  
  
  
  
    {
      "rank": 21,
      "name": "National Institute of Technology - [NIT]",
      "location": "Warangal, Telangana",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,50,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 12,60,000",
      "highest_package": "₹ 51,00,000",
      "placement": "4.4 / 5 Based on 584 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#3th/300 in India The Week 2024"
    },
    {
      "rank": 22,
      "name": "Birla Institute of Technology and Science - [BITS]",
      "location": "Pilani, Rajasthan",
      "approval": "AICTE Approved",
      "fees": "₹ 3,10,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 16,00,000",
      "highest_package": "₹ 1,44,00,000",
      "placement": "4.5 / 5 Based on 962 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#5th/275 in India The Week 2024"
    },
    {
      "rank": 23,
      "name": "Indian Institute of Technology - [IIT]",
      "location": "Roorkee, Uttarakhand",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,21,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 18,00,000",
      "highest_package": "₹ 1,85,00,000",
      "placement": "4.5 / 5 Based on 594 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#5th/31 in India Indiatoday 2024"
    },
    {
      "rank": 24,
      "name": "Institute of Chemical Technology - [ICT]",
      "location": "Mumbai, Maharashtra",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 85,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 6,50,000",
      "highest_package": "₹ 36,00,000",
      "placement": "4.4 / 5 Based on 234 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#15th/300 in India NIRF 2024"
    },
    {
      "rank": 25,
      "name": "IIT Guwahati - Indian Institute of Technology - [IITG]",
      "location": "Guwahati, Assam",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,26,320",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 21,00,000",
      "highest_package": "₹ 1,29,00,000",
      "placement": "4.4 / 5 Based on 434 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#8th/31 in India Indiatoday 2024"
    },
    {
      "rank": 26,
      "name": "Manipal Institute of Technology - [MIT]",
      "location": "Manipal, Karnataka",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 3,20,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,50,000",
      "highest_package": "₹ 43,00,000",
      "placement": "4.2 / 5 Based on 1.2K User Reviews",
      "specialty": "Best in Social Life",
      "ranking": "#9th/275 in India The Week 2024"
    },
    {
      "rank": 27,
      "name": "National Institute of Technology - [NIT]",
      "location": "Surathkal, Karnataka",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,52,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 12,60,000",
      "highest_package": "₹ 70,00,000",
      "placement": "4.5 / 5 Based on 697 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#2th/275 in India The Week 2024"
    },
    {
      "rank": 28,
      "name": "IIT Gandhinagar - Indian Institute of Technology - [IITGN]",
      "location": "Gandhinagar, Gujarat",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,24,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 15,00,000",
      "highest_package": "₹ 60,00,000",
      "placement": "4.4 / 5 Based on 78 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#10th/31 in India Indiatoday 2024"
    },
    {
      "rank": 29,
      "name": "Jadavpur University - [JU]",
      "location": "Kolkata, West Bengal",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,400",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 10,20,000",
      "highest_package": "₹ 48,00,000",
      "placement": "4.4 / 5 Based on 787 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#1th/31 in India The Week 2024"
    },
    {
      "rank": 30,
      "name": "Thapar Institute of Engineering and Technology - [TIET]",
      "location": "Patiala, Punjab",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 3,50,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 9,00,000",
      "highest_package": "₹ 43,00,000",
      "placement": "4.2 / 5 Based on 578 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#6th/275 in India The Week 2024"
    }
  ,
  
  
  
  
  
  
  
  
    {
      "rank": 31,
      "name": "Vellore Institute of Technology - [VIT]",
      "location": "Vellore, Tamil Nadu",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,98,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,30,000",
      "highest_package": "₹ 41,00,000",
      "placement": "4.3 / 5 Based on 5K User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#8th/275 in India The Week 2024"
    },
    {
      "rank": 32,
      "name": "Amity University",
      "location": "Noida, Uttar Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 3,11,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,20,000",
      "highest_package": "₹ 30,00,000",
      "placement": "3.8 / 5 Based on 5K User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#18th/275 in India The Week 2024"
    },
    {
      "rank": 33,
      "name": "Indian Institute of Technology - [IIT]",
      "location": "Indore, Madhya Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,25,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 21,00,000",
      "highest_package": "₹ 60,00,000",
      "placement": "4.5 / 5 Based on 124 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#10th/31 in India Indiatoday 2024"
    },
    {
      "rank": 34,
      "name": "Nirma University - [NU]",
      "location": "Ahmedabad, Gujarat",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,03,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,00,000",
      "highest_package": "₹ 25,00,000",
      "placement": "4.1 / 5 Based on 687 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#14th/275 in India The Week 2024"
    },
    {
      "rank": 35,
      "name": "SRM Institute of Science and Technology - [SRMIST]",
      "location": "Chennai, Tamil Nadu",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,50,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,80,000",
      "highest_package": "₹ 39,00,000",
      "placement": "4.0 / 5 Based on 3K User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#15th/275 in India The Week 2024"
    },
    {
      "rank": 36,
      "name": "IIT BHU - Indian Institute of Technology",
      "location": "Varanasi, Uttar Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,20,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 20,00,000",
      "highest_package": "₹ 1,50,00,000",
      "placement": "4.4 / 5 Based on 623 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#9th/31 in India Indiatoday 2024"
    },
    {
      "rank": 37,
      "name": "College of Engineering - [COEP]",
      "location": "Pune, Maharashtra",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,04,500",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,50,000",
      "highest_package": "₹ 44,00,000",
      "placement": "4.5 / 5 Based on 934 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#16th/300 in India NIRF 2024"
    },
    {
      "rank": 38,
      "name": "National Institute of Technology - [NIT]",
      "location": "Calicut, Kerala",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,25,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 11,50,000",
      "highest_package": "₹ 45,00,000",
      "placement": "4.3 / 5 Based on 497 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#12th/275 in India The Week 2024"
    },
    {
      "rank": 39,
      "name": "Delhi Technological University - [DTU]",
      "location": "New Delhi, Delhi NCR",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,66,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 12,00,000",
      "highest_package": "₹ 1,25,00,000",
      "placement": "4.4 / 5 Based on 1.4K User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#4th/300 in India NIRF 2024"
    },
    {
      "rank": 40,
      "name": "PSG College of Technology - [PSGCT]",
      "location": "Coimbatore, Tamil Nadu",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 89,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,50,000",
      "highest_package": "₹ 30,00,000",
      "placement": "4.2 / 5 Based on 987 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#13th/275 in India The Week 2024"
    },
  
    
    {
      "rank": 41,
      "name": "Birla Institute of Technology - [BIT]",
      "location": "Mesra, Jharkhand",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,05,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,00,000",
      "highest_package": "₹ 35,00,000",
      "placement": "4.2 / 5 Based on 1K User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#17th/275 in India The Week 2024"
    },
    {
      "rank": 42,
      "name": "Jadavpur University",
      "location": "Kolkata, West Bengal",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 40,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,00,000",
      "highest_package": "₹ 20,00,000",
      "placement": "4.1 / 5 Based on 724 User Reviews",
      "specialty": "Best in Research",
      "ranking": "#10th/300 in India NIRF 2024"
    },
    {
      "rank": 43,
      "name": "Manipal Institute of Technology - [MIT]",
      "location": "Manipal, Karnataka",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,00,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 6,00,000",
      "highest_package": "₹ 27,00,000",
      "placement": "4.0 / 5 Based on 876 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#15th/275 in India The Week 2024"
    },
    {
      "rank": 44,
      "name": "Indian Institute of Engineering Science and Technology - [IIEST]",
      "location": "Shibpur, West Bengal",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,95,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 8,00,000",
      "highest_package": "₹ 40,00,000",
      "placement": "4.3 / 5 Based on 652 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#8th/275 in India The Week 2024"
    },
    {
      "rank": 45,
      "name": "SASTRA Deemed University",
      "location": "Thanjavur, Tamil Nadu",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,60,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,50,000",
      "highest_package": "₹ 28,00,000",
      "placement": "4.1 / 5 Based on 564 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#20th/275 in India The Week 2024"
    },
    {
      "rank": 46,
      "name": "Shiv Nadar University - [SNU]",
      "location": "Greater Noida, Uttar Pradesh",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 2,20,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 7,00,000",
      "highest_package": "₹ 32,00,000",
      "placement": "4.0 / 5 Based on 489 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#22nd/275 in India The Week 2024"
    },
    {
      "rank": 47,
      "name": "Netaji Subhas Institute of Technology - [NSIT]",
      "location": "New Delhi, Delhi NCR",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,60,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 11,00,000",
      "highest_package": "₹ 50,00,000",
      "placement": "4.4 / 5 Based on 831 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#7th/31 in India Indiatoday 2024"
    },
    {
      "rank": 48,
      "name": "Birla Institute of Technology and Science - [BITS]",
      "location": "Pilani, Rajasthan",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,80,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 15,00,000",
      "highest_package": "₹ 1,00,00,000",
      "placement": "4.5 / 5 Based on 1.2K User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#2nd/275 in India The Week 2024"
    },
    {
      "rank": 49,
      "name": "R V College of Engineering - [RVCE]",
      "location": "Bengaluru, Karnataka",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,55,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 6,00,000",
      "highest_package": "₹ 32,00,000",
      "placement": "4.0 / 5 Based on 742 User Reviews",
      "specialty": "Best in Infrastructure",
      "ranking": "#18th/275 in India The Week 2024"
    },
    {
      "rank": 50,
      "name": "Vishwakarma Institute of Technology - [VIT]",
      "location": "Pune, Maharashtra",
      "approval": "AICTE, UGC Approved",
      "fees": "₹ 1,15,000",
      "course": "BE/B.Tech- 1st Year Fees",
      "average_package": "₹ 5,00,000",
      "highest_package": "₹ 25,00,000",
      "placement": "4.1 / 5 Based on 634 User Reviews",
      "specialty": "Best in Academics",
      "ranking": "#22nd/275 in India The Week 2024"
    }
  ];
export default collegeData;
